typography_spectrum: 0.00217
color:
  brandColors:
    - '#fffaf6'
    - '#bd969d'
    - '#867588'
    - '#583d36'
    - '#dcc4c4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75163
analytics:
  google: null
  facebook: null
  twitter: null
name: BËRRY - Subtiles confidences
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Belly
    id: 330f5dca-669b-4516-843a-09e1f49def13
    type: content
favicon: null
title: BËRRY - Subtiles confidences
purpose: []
