name: BERRY Portfolio
favicon: null
layout_spectrum: 0.5689177855383605
typography_spectrum: 0.9333888883702457
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8136825708206743
  lightness: 0.5421808217652142
  saturation: 0.3960030027665198
  rhythmicContrast: 0.18779559736140072
purpose: []
