name: BERRY Portfolio
favicon: null
layout_spectrum: 0.75163
typography_spectrum: 0.00217
title: BËRRY - Subtiles confidences
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffaf6'
    - '#bd969d'
    - '#867588'
    - '#583d36'
    - '#dcc4c4'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
