name: BERRY Portfolio
favicon: null
layout_spectrum: 0.75163
typography_spectrum: 0.24924
title: BËRRY - Subtiles confidences
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#982069'
    - '#800080'
    - '#ff0000'
    - '#000000'
    - '#ff00ff'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
